Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1992865-sedona-33 pull request #10
Opened 2022-03-21 20:31 UTC by B1gS1n

---
:mortar_board: [Декоративные элементы на внутренней странице](https://up.htmlacademy.ru/htmlcss/33/user/1992865/tasks/11)

:boom: https://htmlacademy-htmlcss.github.io/1992865-sedona-33/10/

2022-03-22 06:52 UTC, Dima-Dim requested changes
Вернуть описания ссылкам, там где они были удалены. Удалить скрытые описания там где есть не скрытые.

2022-03-22 06:52 UTC, Dima-Dim commented on catalog.html
> +              <svg aria-hidden="true" focusable="false" width="20" height="19" viewBox="0 0 20 19" fill="#000000" xmlns="http://www.w3.org/2000/svg">
Куда исчезло текстовое описание ссылок?

2022-03-22 06:52 UTC, Dima-Dim commented on catalog.html
> +                <span class="visually-hidden"> Применить фильтр гостиниц </span>
Не нужно перебарщивать с описаниями.

2022-03-22 06:52 UTC, Dima-Dim commented on catalog.html
> +            <svg aria-hidden="true" focusable="false" width="16" height="14" viewBox="0 0 16 14" fill="none" xmlns="http://www.w3.org/2000/svg">
Где-то дак 2 описания, а где-то не одного.

2022-03-23 06:46 UTC, Dima-Dim commented on catalog.html
> +                <span class="visually-hidden"> Подробнее о гостинице. </span>
Это избыточные описания.

2022-03-23 06:46 UTC, Dima-Dim commented on catalog.html
> +                <img class="hotel-stars" src="images/catalog-hotel/star.svg" width="18" height="17" alt="звезда.">
Это не контентные изображения. Такое в разметке лучше не оставлять.

2022-03-23 06:46 UTC, Dima-Dim commented on index.html
> +              <span class="visually-hidden"> Поиск </span>
Для чего пробелы вокруг слова Поиск?

2022-03-23 06:46 UTC, Dima-Dim commented on styles/styles.css
>      src: url("/fonts/ptsans-400.woff2") format("woff2");
Не корректный путь до файла с шрифтом, результать можно увидеть в опубликованной версии проекта
https://htmlacademy-htmlcss.github.io/1992865-sedona-33/10/
шрифты не закгружаются.

2022-03-23 06:46 UTC, Dima-Dim commented on styles/styles.css
> +    content:"12";
Это контент который не доступен читалкам и прочему ПО, которые пытается получить доступ к данным на странице.
Кроме того, что нужно будет сделать когда с сервера придёт другая цифра? Использовать класс с другой цифрой?

2022-03-23 06:46 UTC, Dima-Dim commented on styles/styles.css
> +    padding-top: 2.5px;
Точности до целых достаточно.

2022-03-23 06:46 UTC, merged

2022-03-23 11:42 UTC, B1gS1n commented
Все исправлю. Сегодня отправлю последнее задание. Возможно ли сейчас уже проверить для защиты, т. к. основа уже сделана?

2022-03-23 12:05 UTC, B1gS1n commented on styles/styles.css
> +    content:"12";
Тогда как это лучше и правильнее реализовать?

2022-03-23 12:17 UTC, B1gS1n commented on styles/styles.css
>      src: url("/fonts/ptsans-400.woff2") format("woff2");
Вроде такой же шрифт, как и в макете. Не пойму, в чем ошибка подключения?

2022-03-23 12:39 UTC, B1gS1n commented on catalog.html
> +                <img class="hotel-stars" src="images/catalog-hotel/star.svg" width="18" height="17" alt="звезда.">
Разве изображение не несет для пользователя никакой информации?

2022-03-23 17:43 UTC, Dima-Dim commented on styles/styles.css
> +    content:"12";
К концу курса было бы хорошо, если бы ты предложил варианты о которых узнал за эти 2 месяца.

2022-03-23 21:28 UTC, B1gS1n commented on styles/styles.css
> +    content:"12";
Разве нельзя поменять св-во content через атрибут style="" напрямую в html

2022-03-23 21:29 UTC, B1gS1n commented on styles/styles.css
> +    content:"12";
Я пока что своим без опытным взглядом не увидел другого варианта

2022-03-24 06:27 UTC, Dima-Dim commented on styles/styles.css
> +    content:"12";
С учётом моего комментария можно сделать вывод что контент всё же должен быть в разметке. И это первое что нужно сделать. А далее эту разметку уже стилизовать.

> Разве нельзя поменять св-во content через атрибут style="" напрямую в html

Можно придумать много ужасно сложных вариантов, но делают так обычно бекендеры, которые не хотят разобраться с вёрсткой. Именно по этому есть курс по HTML, которые помогает разобраться и понять что довольно многое можно сделать очень просто, использую нативные технологи, в частности html.

2022-03-24 06:28 UTC, Dima-Dim commented on catalog.html
> +                <img class="hotel-stars" src="images/catalog-hotel/star.svg" width="18" height="17" alt="звезда.">
Контентное изображение да, несёт. А какую информацию несёт это изображение?

2022-03-24 06:29 UTC, Dima-Dim commented on styles/styles.css
>      src: url("/fonts/ptsans-400.woff2") format("woff2");
Ошибка в "Не корректный путь до файла с шрифтом" :) Ну и дальше по тексту тоже полезная информация, чтобы можно было в этом удостовериться.

2022-03-24 06:30 UTC, Dima-Dim commented
Возможно.

2022-03-24 11:08 UTC, B1gS1n commented on catalog.html
> +                <img class="hotel-stars" src="images/catalog-hotel/star.svg" width="18" height="17" alt="звезда.">
Информацию о количестве звезд у гостинице-престиже гостиницы

2022-03-24 11:34 UTC, B1gS1n commented
Это через сайт академии в защите нужно оправить?

2022-03-24 12:53 UTC, Dima-Dim commented on catalog.html
> +                <img class="hotel-stars" src="images/catalog-hotel/star.svg" width="18" height="17" alt="звезда.">
На данных изображениях нет ничего не про количество, не про пристиж. Это просто изображения звезды, очень абстрактной звезды. И это изображение ещё и продублировано в разметке несколько раз.

2022-03-24 12:54 UTC, Dima-Dim commented
Да, через личный кабинет Академии.