Седона: разметка главной страницы
htmlacademy-htmlcss/1992865-sedona-33 pull request #2
Opened 2022-01-27 09:49 UTC by B1gS1n

2022-01-27 15:06 UTC, Dima-Dim requested changes

2022-01-27 15:06 UTC, Dima-Dim commented on index.html
> +              <img src="" alt="Эмблема CITY OF SEDONA, на главную страницу">
По сути это логоти сам по себе и очень не похож на остальные пунты меню.

2022-01-27 15:06 UTC, Dima-Dim commented on index.html
> +      <br>
Это про оформление и стилизацию, а её мы сейчас не делаем.А когда будем делать, будем делать иначе.

2022-01-27 15:06 UTC, Dima-Dim commented on index.html
> +      <h2 class="visually-hidden">
Явно не не хватает контнейнера в виде section.

2022-01-27 15:06 UTC, Dima-Dim commented on index.html
> +        ПОДПИШИСЬ НА РАССЫЛКУ
Тексты пишем как в побычных предложениях, стилизовать будем позже и с помощью CSS.

2022-01-27 15:06 UTC, Dima-Dim commented on index.html
> +      <section class="footer-contact">
А вот тут section и заголовки избыточны.

2022-01-29 13:03 UTC, B1gS1n commented on index.html
> +              <img src="" alt="Эмблема CITY OF SEDONA, на главную страницу">
Значит нужно просто логотип просто вынести за список?!

2022-01-29 13:04 UTC, u1Test commented on index.html
> +              <img src="" alt="Эмблема CITY OF SEDONA, на главную страницу">
Да.

2022-01-29 13:05 UTC, Dima-Dim commented on index.html
> +              <img src="" alt="Эмблема CITY OF SEDONA, на главную страницу">
Да.

2022-01-29 13:10 UTC, B1gS1n commented on index.html
> +      <br>
Что Именно? Про 52 строчку или <img>?

2022-01-29 13:27 UTC, B1gS1n commented on index.html
> +      <h2 class="visually-hidden">
Имеется в виду весь <h2> с 153 до до 163 нужно в <section>?

2022-01-29 13:42 UTC, B1gS1n commented on index.html
> +      <section class="footer-contact">
Здесь возможно вместо <section> тег <address> использовать

2022-01-29 13:52 UTC, B1gS1n commented on index.html
> +      <section class="footer-contact">
вместо section тег address использовать

2022-01-29 14:05 UTC, Dima-Dim commented on index.html
> +      <h2 class="visually-hidden">
Имеется ввиду для блока который ты назвал "Поиск гостиницы".

2022-01-29 14:05 UTC, Dima-Dim commented on index.html
> +      <section class="footer-contact">
Прям сейчас можно просто убрать тег section и скрытый заголовок.

2022-01-29 14:21 UTC, B1gS1n commented on index.html
> +      <br>
или img?

2022-01-29 15:29 UTC, Dima-Dim commented on index.html
> +      <br>
Этот комментарий к 55-ой строке с тегом `<br>`.

2022-01-31 06:46 UTC, Dima-Dim approved these changes

2022-01-31 06:46 UTC, merged