Графика для всех страниц
htmlacademy-htmlcss/1992865-sedona-33 pull request #4
Opened 2022-02-08 16:02 UTC by B1gS1n

---
:mortar_board: [Графика для всех страниц](https://up.htmlacademy.ru/htmlcss/33/user/1992865/tasks/5)

:boom: https://htmlacademy-htmlcss.github.io/1992865-sedona-33/4/

2022-02-09 05:33 UTC, Dima-Dim requested changes
Убрать декоративные изображения из разметки.

2022-02-09 05:33 UTC, Dima-Dim commented on catalog.html
> +                <img src="images/head/search.svg" width="42" height="66" href="#" alt="Поиск гостиниц">
https://htmlacademy.ru/blog/boost/frontend/content-or-decor-img

2022-02-09 05:33 UTC, Dima-Dim commented on catalog.html
> +          <h2 class="visually-hidden">
За одно, тут не нужна ни секция, ни заголовок. Тут будет только контентое изображение с alt, в котором есть его описание.

2022-02-09 10:44 UTC, B1gS1n commented on catalog.html
> +                <img src="images/head/search.svg" width="42" height="66" href="#" alt="Поиск гостиниц">
По сути тогда нужно оставить на первой странице:
2 фотографии-продаваемый объект 
logo
logo htmlacademy
На второй странице:
фото гостиниц
logo htmlacademy?

2022-02-09 10:50 UTC, Dima-Dim commented on catalog.html
> +                <img src="images/head/search.svg" width="42" height="66" href="#" alt="Поиск гостиниц">
Нет, на главной странице будет больше изображений, так же как и на внутренний. Все логотипы это контентные изображения.

2022-02-10 06:38 UTC, Dima-Dim approved these changes

2022-02-10 06:38 UTC, merged