Добавление базовой стилизации
htmlacademy-htmlcss/1992865-sedona-33 pull request #5
Opened 2022-02-18 19:25 UTC by B1gS1n

2022-02-19 04:59 UTC, Dima-Dim requested changes
Не забываем проверять как выглядит опубликованная версия. Для данного пулрриквеста это https://htmlacademy-htmlcss.github.io/1992865-sedona-33/5/
Там то, что смотрю я и оно должно быть таким же как ты видишь это у себя локально.

2022-02-19 04:59 UTC, Dima-Dim commented on .gitignore
> +styles/styles.css
Зачем?

2022-02-19 04:59 UTC, Dima-Dim commented on catalog.html
> +              <span class="Housing-type">
Названиях классов тоже не нужно использовать разные регистры букв.

2022-02-19 04:59 UTC, Dima-Dim commented on catalog.html
> +        <p class="contact"> <a class="contack-phone" href="tel:+78128121212">+7 (812) 812-12-12</a> </p>
Для чего появилась лишняя обёртка?

2022-02-19 04:59 UTC, Dima-Dim commented on index.html
> +            Сайт бронирования гостиниц в городе Sedona
Почему изменился отступ?

2022-02-19 04:59 UTC, Dima-Dim commented on index.html
> +        <p >
Зачем пробелы перед `>`.

2022-02-19 04:59 UTC, Dima-Dim commented on index.html
> +        <img class="welcome" src="/images/welcome.svg" width="458" height="352" alt="Приветствие в городе Sedona"></p>
Почему `</p>` не на своей строке? Открывается же он на своей.

2022-02-19 04:59 UTC, Dima-Dim commented on index.html
> +        <p class="b"> Седона — небольшой городок в Аризоне, заслуживающий большего!</p>
Класс `b`? В атомик css есть что-то подобное, но я бы не рекомендовал так делать. Это приведёт либо к большому количеству классов на элементе, либо к большому количеству дублирующихся свойств у разных классов. И точно не добавит понятности.

2022-02-19 04:59 UTC, Dima-Dim commented on index.html
> +              <li class="advanteges-block dark-blue-12-cube souvenirs">
`dark-blue-12-cube` - не нужно называть классы по тому как выглядит стилизация которую они несут. Нужно стараться понять назначение этой стилизации. Вам на лайве это должны были рассказывать. Рекомендую подумать пресмотреть этот материал и подумать над названиями.

2022-02-19 04:59 UTC, Dima-Dim commented on index.html
> +                    Не только китайского, но и настоящего местного производства!
Тоже какой непонятный отступ появился.

2022-02-19 04:59 UTC, Dima-Dim commented on index.html
> +        <p class="knopka"> <a class="button button-hotel-search" href="catalog.html">Поиск гостиницы в Седоне</a></p>
`knopka` - не вижу это в критериях, но этот транслит, который точно не нужно использовать ни для чего.

2022-02-19 04:59 UTC, Dima-Dim commented on index.html
> +      <h2 class="mailing-list">
h2 вложен в div, значит отступ у него должен быть больше чем у div.
Настрой и используй .editorconfig

2022-02-19 04:59 UTC, Dima-Dim commented on styles/styles.css
> +.fon {
Тоже транслит и тоже странный класс только для фона. Для чего нужен класс для фона если "фон" его можно применить к любому другому классу?

2022-02-19 04:59 UTC, Dima-Dim commented on styles/styles.css
> +    height: 36px;
Название класса намекает что оно для какого то текста. О самих таких названиях я уже много написал. А ограничение высоты для текста это проблемы при переполнении.

2022-02-19 04:59 UTC, Dima-Dim commented on styles/styles.css
> +    height: 384px;
Тоже высота, которая приведёт к проблемам при переполнении. Это касается всех блоков с текстом.

2022-02-19 04:59 UTC, Dima-Dim commented on styles/styles.css
> +.benefits-description-souvenirs{
Где-то есть пробел перед { где-то нет. Должно быть одинаково.

2022-02-19 04:59 UTC, Dima-Dim commented on styles/styles.css
> +    background-color: #83B3D3;
Где-то используются большие буквы в названиях цветом, где-то маленькие. Тоже должно быть одинаково.

2022-02-19 04:59 UTC, Dima-Dim commented on styles/styles.css
> +    color:#ffffff;
Белый текст на белом фоне?

2022-02-19 18:19 UTC, B1gS1n commented on .gitignore
> +styles/styles.css
Я даже не знаю что это такое, и откуда. У меня gitHub, при создании пулреквеста создал 4 папки, все напортил, по этому пришлось все править, появились пробелы и почему то, не могу понять почему, не показывает изображения, хотя в VScode, включая LiveServer все изображения на месте, почему?

2022-02-20 09:03 UTC, Dima-Dim commented on .gitignore
> +styles/styles.css
Не припомню на своей практике чтобы GitHub сам брал что либо и портил. Это просто веб интерфейс над git-репозиторием, в который ты что либо отправляешь или забираешь.
Изображения не отображаются потому, что до них не верные пути, это можно увидеть открыв девтулз в браузере и посмотреть вкладку Network. И по девтулзам и по путям у вас должен быть материал и на лайве это тоже должны были упоминать.

2022-02-21 16:59 UTC, B1gS1n commented on .gitignore
> +styles/styles.css
Если Изображение вставлять через тег <img> - то изображение есть, а если его же через CSS background-image, то не отображается? Может ли какая проблема в CSS, не могу разобраться.

2022-02-21 17:10 UTC, Dima-Dim commented on .gitignore
> +styles/styles.css
Проблема в том, что папка с изображениями расположена по разному относительно файла index.html и styles.css, стало быть и пути до изображений будут разные.

2022-02-22 10:31 UTC, B1gS1n commented on styles/styles.css
> +    height: 384px;
Тогда как задавать высоту блока?

2022-02-22 13:08 UTC, Dima-Dim commented on styles/styles.css
> +    height: 384px;
Через размеры из которых она состоит. padding-и и line-height-и. line-height должны соответствовать макету, а вот padding-и можно задать какие нужно. Бывают случае когда высота может быть задана через min-height.

2022-02-22 16:37 UTC, B1gS1n commented on styles/styles.css
> +.fon {
Название-согласен, а вот фон-в смысле вставить фон не в отдельный класс?

2022-02-23 10:02 UTC, B1gS1n commented on styles/styles.css
> +    height: 384px;
Как раз этого нам не объясняли

2022-02-23 11:32 UTC, B1gS1n commented on styles/styles.css
> +    height: 384px;
Я так понимаю, про padding и позиционирование в этом задании не нужно, и на этой стадии это не важно

2022-02-23 17:29 UTC, B1gS1n commented on styles/styles.css
> +    height: 36px;
название говорит, что черный цвет текста в преимуществах.

2022-02-24 06:36 UTC, Dima-Dim commented on styles/styles.css
> +    height: 384px;
Мне важно на это обратить внимание, тебе важно об этом узнать. Когда внести эти правки, решать тебе.

2022-02-24 06:37 UTC, Dima-Dim commented on styles/styles.css
> +    height: 36px;
А когда дизайнер решит что цвет должен быть серый? Будешь менять и цвет и название класса?

2022-02-24 08:12 UTC, Dima-Dim requested changes

2022-02-24 08:12 UTC, Dima-Dim commented on .gitignore
> +styles/styles.css
"styles/styles.css" всё ещё не убрано из .gitignore

2022-02-24 08:12 UTC, Dima-Dim commented on index.html
> +        <p>
Для чего тут два контейнера `div` и `p`?

2022-02-24 08:12 UTC, Dima-Dim commented on index.html
> +                    Не только китайского, но и настоящего местного производства!
Отступ тоже не поправлен.

2022-02-24 08:12 UTC, Dima-Dim commented on index.html
> +              <h3 class="advanteges-title advanteges-title-black">
Здесь с отступом было нормально, а теперь h3 по отступам на одном уровне с div, хотя h3 вложен в div.

2022-02-24 08:12 UTC, Dima-Dim commented on index.html
> +      <h2 class="mailing-list">
Тоже не поправлено.

2022-02-24 08:12 UTC, Dima-Dim commented on styles/styles.css
> +    src: url("fonts/pt-sans-regular.woff2") format("woff2");
Папк с шрифтами не находтся на одном уровне с css.

2022-02-24 08:12 UTC, Dima-Dim commented on styles/styles.css
> +.benefits-description-souvenirs{
Тоже не поправлено.

2022-02-24 10:54 UTC, B1gS1n commented on index.html
> +        <p>
Моя ошибка, не доглядел и забыл удалить

2022-02-25 04:25 UTC, merged