построение сетки на гридах в каталоге
htmlacademy-htmlcss/1992865-sedona-33 pull request #8
Opened 2022-03-15 13:08 UTC by B1gS1n

2022-03-16 06:19 UTC, Dima-Dim requested changes

2022-03-16 06:19 UTC, Dima-Dim commented on catalog.html
> +              <form action="https://echo.htmlacademy.ru/courses" method="get">
Нет тут формы, как минимум потому, что тут нет никаких полей.

2022-03-16 09:16 UTC, B1gS1n commented on catalog.html
> +              <form action="https://echo.htmlacademy.ru/courses" method="get">
Извините, здесь не понял ошибку?

2022-03-16 17:13 UTC, Dima-Dim commented on catalog.html
> +              <form action="https://echo.htmlacademy.ru/courses" method="get">
Почему ты решил что здесь нужна форма?

2022-03-16 17:36 UTC, B1gS1n commented on catalog.html
> +              <form action="https://echo.htmlacademy.ru/courses" method="get">
Разве не нужно отправлять эту информацию на сервер?

2022-03-17 07:15 UTC, Dima-Dim commented on catalog.html
> +                <img class="hotel-stars" src="images/catalog-hotel/star.svg" width="18" height="17" alt="звезда">
https://up.htmlacademy.ru/htmlcss/33/module/2/item/19

2022-03-17 07:15 UTC, merged

2022-03-17 07:30 UTC, Dima-Dim commented on catalog.html
> +              <form action="https://echo.htmlacademy.ru/courses" method="get">
Что будет содержать эта форма? Какие поля, с какими данными?